<a href="https://colab.research.google.com/github/safwaanh/lighthouse-python-fundamentals/blob/master/basic_operations_with_matrices__exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TASK:** import numpy

In [0]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [0]:
x = np.array([1,2,3])
x

array([1, 2, 3])

**TASK:** define (2 x 2) matrix 'A' 


In [0]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

**TASK:** define (2 x 2) matrix 'B'

In [0]:
B = np.array([[5,6],[7,8]])
B

array([[5, 6],
       [7, 8]])

**TASK:** check the type of 'x'

In [0]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [0]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [0]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [0]:
A.shape

(2, 2)

**TASK:** 

In [0]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

In [0]:
def have_same_shape(array_1, array_2):
  condition = False

  if array_1.shape == array_2.shape:
    condition = True

  if condition == False:
    print("Arrays must have the same shape!")

  return condition

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [0]:
have_same_shape(A,x)

Arrays must have the same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [0]:
have_same_shape(A,B)

True

**TASK:** 

In [0]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [0]:
def matrix_addition(A,B):
  if have_same_shape(A,B) == True:
    C = A + B

  return C

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [0]:
matrix_addition(A,B)

array([[ 6,  8],
       [10, 12]])

**TASK:** 

In [0]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [0]:
def multiple_matrix_addition(lst_of_arr):
  shape_matrix = lst_of_arr[0].shape
  D = np.zeros(shape_matrix)
  
  for i in range(len((lst_of_arr))-1):
    D += matrix_addition(lst_of_arr[i], lst_of_arr[i+1])

  return D



**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [0]:
arr_list = [A,A,B,B,B]
multiple_matrix_addition(arr_list)

array([[28., 36.],
       [44., 52.]])

**TASK:** 

In [0]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [0]:
shape_A = A.shape
type(shape_A)

shape_A[1] 

2

In [0]:
def can_multiply(array_a, array_b):
  shape_A = array_a.shape
  shape_B = array_b.shape
  condition = False

  if shape_A[1] == shape_B[0]:
    condition = True
    C = array_a.dot(array_b)
    print(C.shape)

  else:
    print("Matrices cannot be multiplied")

  return condition

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [0]:
can_multiply(A,B)

(2, 2)


True

**TASK:**  define matrix (3 x 2) matrix C

In [0]:
C = np.array([[1,2],[3,4],[5,6]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [0]:
can_multiply(A,C)

Matrices cannot be multiplied


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [0]:
can_multiply(C,A)

(3, 2)


True

**TASK:** 

In [0]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [0]:
def matrix_multiplication(array_a, array_b):
  if can_multiply(array_a, array_b) == True:
    NEW_ARRAY = array_a.dot(array_b)
  else:
    return None

  return NEW_ARRAY

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [0]:
matrix_multiplication(C,B)

(3, 2)


array([[19, 22],
       [43, 50],
       [67, 78]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [0]:
matrix_multiplication(A, C)

Matrices cannot be multiplied
